name: Run TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Firefox 128.0
      run: |
        wget https://ftp.mozilla.org/pub/firefox/releases/128.0/linux-x86_64/en-US/firefox-128.0.tar.bz2
        tar xjf firefox-128.0.tar.bz2
        sudo mv firefox /opt/firefox-128.0
        sudo ln -s /opt/firefox-128.0/firefox /usr/local/bin/firefox

    - name: Install GeckoDriver
      run: |
        GECKODRIVER_VERSION=v0.34.0
        wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver
        geckodriver --version
    
    # - name: Build and package the application
    #   run: mvn clean install

    - name: Start the server in the background
      run: |
        mvn clean verify -P server-up &
        echo $! > server.pid

    - name: Wait for the server to start
      run: sleep 5

    - name: Run TestNG Tests
      run: mvn test -Pe2e

    - name: Stop the server
      run: |
        kill $(cat server.pid)
        rm server.pid
    
    - name: Upload Emailable Report
      uses: actions/upload-artifact@v3
      with:
        name: emailable-report
        path: target/surefire-reports/emailable-report.html